on: [push, pull_request]
name: lint and test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Install cache
        uses: Swatinem/rust-cache@v1

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all --tests

      - name: test
        run: cargo test
        env:
          RUST_LOG: debug
          RUST_BACKTRACE: 1

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy

      - name: Install cache
        uses: Swatinem/rust-cache@v1

      - name: Run clippy manually without annotations
        run: cargo clippy --tests --all-targets -- -D warnings
        env:
          RUSTFLAGS: "--cfg tokio_unstable --cfg test_systemd_run"
